### ISSUE TITLE
Support for other operators like ||=

### ISSUE THREAD

**Issue by unmultimedio** [adrianlee44/atom-aligner-ruby#4]
I'd love to use `||=` as an _alignable_ operator.

Right now only supports `=` and `+=`, `-=`.

Or, can you point me to the right setting? Can't find a way to list all _valid_ operators.

**Comment by adrianlee44** [comment]
@unmultimedio. Will need a code change for this.

I'm considering these as valid operators,
`'<<=|%=|&{1,2}=|\\*=|\\*\\*=|\\+=|-=|\\^=|\\|{1,2}='` and `/=`.

These are taken from the ruby grammar. Am I missing any?

**Comment by adrianlee44** [comment]
Bumped this package to v1.5.0. Please let me know if it works. Thanks.

**Comment by unmultimedio** [comment]
Awesome it works! 😎
