### ISSUE TITLE
align multiple hash keys in an array of hashes?

### ISSUE THREAD

**Issue by NullVoxPopuli** [adrianlee44/atom-aligner-ruby#5]
Say I have a structure:

``` ruby
[
  { a: 1, b: 2 },
  { a: 'one', b: 'two' }
]
```

I'd like to be able to convert it to:

``` ruby
[
  { a: 1,     b: 2 },
  { a: 'one', b: 'two' }
]
```

**Comment by adrianlee44** [comment]
Hi @NullVoxPopuli. The current implement of aligner will not be able to support this as `:` is taking priority here. I'll get back to you when I have an update.

**Comment by contentfree** [comment]
Any update on this? It's really my most-used type of alignment

**Comment by goalaleo** [comment]
I'd also love to see support for this

**Comment by Loschcode** [comment]
Same here, is there any update ?
