### ISSUE TITLE
Align commas on multiple lines

### ISSUE THREAD

**Issue by goalaleo** [adrianlee44/atom-aligner-ruby#7]
Is it possible to align commas if there are multiple commas per line? e.g.
```
# FROM
[
  [1, "a string", 20],
  [13, "aother string", 555]
]
# TO
[
  [1 , "a string"      , 20],
  [13, "another string", 555]
]
```

**Comment by adrianlee44** [comment]
This is a supported feature for Javascript. Let me see if the ruby grammar package allows me to do so.
