### ISSUE TITLE
hash rocket alignment no longer works?

### ISSUE THREAD

**Issue by aarnwri** [adrianlee44/atom-aligner-ruby#8]
I'm on Atom 1.55.0, aligner 1.2.4, and aligner-ruby 1.7.0, and if I have a hash:
```
  hash = {
    :short_key => "some random string",
    :looooonng_key => "some other random string",
  }
```

It aligns the commas, but not the hash rockets:
```
  hash = {
    :short_key => "some random string"          , 
    :looooonng_key => "some other random string", 
  }
```

I care a lot more about hash rocket alignment... It's also adding a space to the right of the comma, which seems kinda weird in this case. I'm using default settings, so I'm thinking maybe this broke in a recent update?

**Comment by adrianlee44** [comment]
Hi @aarnwri, 1.8.0 should fix the issue. Let me know if you are still running into issues.

**Comment by aarnwri** [comment]
Thanks @adrianlee44! It does work better. If I have one key that points to a hash containing a rocket, it will line up with the second rocket instead of the first. I don't think it used to do this, but maybe I should just be putting nested hashes on new lines... So it will look something like this:

```
my_hash = {
  :some_key                        => "some_val",
  :some_key_2 => {:some_nested_key => "some_nested_val"}
}
```

Not as big a deal, since I don't often use this, and I could just put it on another line.

Thanks again for the quick fix!
